
CONFIG_ZMK_KEYBOARD_NAME="WoooL"
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
# CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=3600

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_RGBLED_WIDGET=y
CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
